<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/03/06 11:34:10
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'baseform' => 'C:/xampp/htdocs/VDM_Project_LicencePro/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => 'C:/xampp/htdocs/VDM_Project_LicencePro/apps/frontend/lib/myUser.class.php',

  // modules
);
